# ---------------------------------------------------------------------------
# meta-silviolinux :: conf/layer.conf
# Camada Yocto/OpenEmbedded do SilvioLinux Minimal
# Baseado no Poky 5.0 "Scarthgap" (Yocto Project 5.0 LTS)
# ---------------------------------------------------------------------------

# Verifica se é uma camada compatível com bitbake >= 6 (Scarthgap)
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "silviolinux"
BBFILE_PATTERN_silviolinux = "^${LAYERDIR}/"
BBFILE_PRIORITY_silviolinux = "10"

LAYERSERIES_COMPAT_silviolinux = "scarthgap"

LAYERDEPENDS_silviolinux = "core"

LAYERVERSION_silviolinux = "1"

# Nome amigável exibido em `bitbake-layers show-layers`
BBLAYERS_LAYERINDEX_NAME_silviolinux = "meta-silviolinux"
