# /etc/opkg/opkg.conf
# Configuração principal do opkg - SilvioLinux Minimal 1.0 (Aurora)

# Arquitetura de destino (32-bit)
arch all 1
arch i586 10
arch silviolinux-i586 12

# Inclui os feeds definidos separadamente
include /etc/opkg/opkg-feeds.conf
include /etc/opkg/aurora.conf

# Diretórios de trabalho do opkg
dest root /
dest ram /dev/shm

lists_dir ext /var/lib/opkg/lists
option tmp_dir /var/tmp
option cache_dir /var/cache/opkg

# Não instala pacotes 'recommends' automaticamente (mantém o sistema enxuto)
option no_install_recommends 1
option check_signature 1
